### ISSUE TITLE
Update to latest hoodie conventions

### ISSUE THREAD

**Issue by inator** [hoodiehq/hoodie-task#2]
See https://github.com/hoodiehq/camp/issues/100

**Comment by gr2m** [comment]
the Hoodie conventions are that we pass a PouchDB constructor as options to the Hapi plugin, see [hoodie options](https://github.com/hoodiehq/hoodie#hapi-plugin), [@hoodie/account-server options](https://github.com/hoodiehq/hoodie-account-server/blob/master/plugin/README.md#optionspouchdb) and [@hoodie/account-store options](https://github.com/hoodiehq/hoodie-store-server#optionshooks) for comparison

**Comment by gr2m** [comment]
@mbad0la do you want to look into this?
